<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[CDcc]]>
    </line>
  </reporter-output>
  <suite name="Parallel test suite" duration-ms="25348" started-at="2020-07-13T18:02:19 IST" finished-at="2020-07-13T18:02:45 IST">
    <groups>
    </groups>
    <test name="exampletest1" duration-ms="25348" started-at="2020-07-13T18:02:19 IST" finished-at="2020-07-13T18:02:45 IST">
      <class name="rest.Demo">
        <test-method status="PASS" signature="setup()[pri:0, instance:rest.Demo@1e965684]" name="setup" is-config="true" duration-ms="160" started-at="2020-07-13T18:02:19 IST" finished-at="2020-07-13T18:02:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="start(java.lang.reflect.Method)[pri:0, instance:rest.Demo@1e965684]" name="start" is-config="true" duration-ms="11" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void rest.Demo.test1()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="start(java.lang.reflect.Method)[pri:0, instance:rest.Demo@1e965684]" name="start" is-config="true" duration-ms="14" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void rest.Demo.test3()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="start(java.lang.reflect.Method)[pri:0, instance:rest.Demo@1e965684]" name="start" is-config="true" duration-ms="13" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void rest.Demo.test4()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="start(java.lang.reflect.Method)[pri:0, instance:rest.Demo@1e965684]" name="start" is-config="true" duration-ms="11" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void rest.Demo.test2()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:rest.Demo@1e965684]" name="test2" duration-ms="11901" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:31 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at rest.Demo.test2(Demo.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:rest.Demo@1e965684]" name="test1" duration-ms="18841" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:38 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at rest.Demo.test1(Demo.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[CDcc]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:rest.Demo@1e965684]" name="test3" duration-ms="18902" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:38 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at rest.Demo.test3(Demo.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="FAIL" signature="test4()[pri:0, instance:rest.Demo@1e965684]" name="test4" duration-ms="22506" started-at="2020-07-13T18:02:20 IST" finished-at="2020-07-13T18:02:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at rest.Demo.test4(Demo.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:rest.Demo@1e965684]" name="tearDown" is-config="true" duration-ms="9030" started-at="2020-07-13T18:02:31 IST" finished-at="2020-07-13T18:02:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=FAILURE method=Demo.test2()[pri:0, instance:rest.Demo@1e965684] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:rest.Demo@1e965684]" name="tearDown" is-config="true" duration-ms="4549" started-at="2020-07-13T18:02:38 IST" finished-at="2020-07-13T18:02:43 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=FAILURE method=Demo.test1()[pri:0, instance:rest.Demo@1e965684] output=CDcc]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:rest.Demo@1e965684]" name="tearDown" is-config="true" duration-ms="3561" started-at="2020-07-13T18:02:38 IST" finished-at="2020-07-13T18:02:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test3 status=FAILURE method=Demo.test3()[pri:0, instance:rest.Demo@1e965684] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:rest.Demo@1e965684]" name="tearDown" is-config="true" duration-ms="1511" started-at="2020-07-13T18:02:42 IST" finished-at="2020-07-13T18:02:44 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test4 status=FAILURE method=Demo.test4()[pri:0, instance:rest.Demo@1e965684] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="write()[pri:0, instance:rest.Demo@1e965684]" name="write" is-config="true" duration-ms="1082" started-at="2020-07-13T18:02:44 IST" finished-at="2020-07-13T18:02:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- write -->
      </class> <!-- rest.Demo -->
    </test> <!-- exampletest1 -->
  </suite> <!-- Parallel test suite -->
</testng-results>
